### ISSUE TITLE
Project Arrangement:

### ISSUE THREAD

**Issue by M-Anwar-Hussaini** [M-Anwar-Hussaini/JavaScriptCapstone#21]
# Details of this Capstone project:

## Authors:
- @M-Anwar-Hussaini
- @sergio-usma

## Project link:
- We will work on [this](https://github.com/M-Anwar-Hussaini/JavaScriptCapstone/) project.

## Task Distribution:
- Student A: @M-Anwar-Hussaini
- Student B: @sergio-usma

**Comment by Shedrack-Sunday** [comment]
Hello @M-Anwar-Hussaini      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice work with the setup✔️   
  
# Required Changes  🌵 

- [x] Kindly assign the cards to each member of the team. At this point, no card has been assigned yet
### Your cards:
![image](https://github.com/M-Anwar-Hussaini/JavaScriptCapstone/assets/50990925/2444598f-d1d1-4470-b088-735b1acd4014)

### Expected:
![image](https://github.com/M-Anwar-Hussaini/JavaScriptCapstone/assets/50990925/6c7aaba8-6177-44a4-960f-7a61178ee6b9)

- [ ] Please use the correct link to direct to your project which is [This Link](https://github.com/M-Anwar-Hussaini/JavaScriptCapstone/projects/1). The one you provided leads to your main repository bu not the cards 👍 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).










https://github.com/M-Anwar-Hussaini/JavaScriptCapstone/projects/1

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start your capstone :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- Kanban board is correctly set up ✔️ ✔️ 
- All tasks have been assigned to a member 👏 👏 
- All tasks are fairly assigned and distributed 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
